2024-06-12 18:14:22,744 - django.request - WARNING - Not Found: /
2024-06-12 18:20:07,392 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/setting/settings.py changed, reloading.
2024-06-12 18:30:39,723 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/services/ocr_service.py changed, reloading.
2024-06-12 18:33:24,009 - django.request - WARNING - Not Found: /ocr/ocr_page_table/
2024-06-12 18:33:41,423 - django.request - WARNING - Not Found: /ocr/ocr_page/401/vs/base/worker/workerMain.js
2024-06-12 18:33:53,268 - django.request - WARNING - Not Found: /ocr/ocr_page/405/vs/base/worker/workerMain.js
2024-06-12 18:43:38,379 - django.request - WARNING - Not Found: /ocr/ocr_page/405/vs/base/worker/workerMain.js
2024-06-12 18:45:41,457 - django.request - ERROR - Internal Server Error: /ocr/ocr_page/405/
Traceback (most recent call last):
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'ocr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py", line 83, in get
    return render(request, self.template_name, context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'ocr' is not a registered namespace
2024-06-12 18:46:10,248 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/setting/urls.py changed, reloading.
2024-06-12 18:51:24,595 - django.request - ERROR - Internal Server Error: /ocr/ocr_page/405/
Traceback (most recent call last):
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py", line 83, in get
    return render(request, self.template_name, context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'ocr_page_list' with keyword arguments '{'project_id': ''}' not found. 1 pattern(s) tried: ['ocr/ocr_page/\\Z']
2024-06-12 18:52:19,510 - django.request - WARNING - Not Found: /ocr/ocr_page/405/vs/base/worker/workerMain.js
2024-06-12 18:55:45,465 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/urls.py changed, reloading.
2024-06-12 18:56:19,689 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/urls.py changed, reloading.
2024-06-12 18:57:48,580 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 18:57:50,431 - django.request - ERROR - Internal Server Error: /ocr/ocr_page/
Traceback (most recent call last):
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py", line 49, in get_context_data
    context['table'] = OcrPageTable(self.object_list)
  File "/Users/panagoa/PycharmProjects/zbze_ocr/venv/lib/python3.10/site-packages/django_tables2/tables.py", line 282, in __init__
    raise TypeError(f"Argument data to {type(self).__name__} is required")
TypeError: Argument data to OcrPageTable is required
2024-06-12 18:58:13,074 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 18:59:21,754 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 19:00:31,224 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 19:08:54,800 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 19:12:21,698 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 19:12:40,110 - django.utils.autoreload - INFO - /Users/panagoa/PycharmProjects/zbze_ocr/web/ocr_viewer/app/ocr/views/base_views.py changed, reloading.
2024-06-12 19:16:59,428 - django.request - WARNING - Not Found: /ocr/ocr_page/403/vs/base/worker/workerMain.js
2024-06-12 19:17:09,812 - django.request - WARNING - Not Found: /ocr/ocr_page/413/vs/base/worker/workerMain.js
